import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, { Fragment } from 'react'
import { TextContainer } from '../components/textContainer'
import alex from '../img/alex.png'

const Home: NextPage = () => {
  return (
    <div className='w-full h-sceen'>
      <Head>
        <title>Form Anglais</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-screen w-full bg-gradient-to-b from-red-500 to bg-purple-600'>
        <div className='flex justify-center items-center'>
          <div className='flex justify-center p-6 items-start w-5/12 h-1/2'>
            <div className='flex items-center flex-col'>
              <div className='bg-indigo-500/60 shadow-xl rounded-full items-baseline flex w-80 h-80 absolute mt-9' />
              <Image src={alex} width={400} height={300} alt='Alexandra Roque' className='z-10' />
              <div className='p-2 bg-white rounded-xl shadow-xl w-96 flex justify-center items-center flex-col -mt-6 z-20'>
                <h2 className='text-4xl font-semibold text-blue-900'>Alexandra Roque</h2>
                <span className='text-baseColor-100'>Auto-Entrepreneuse</span>
              </div>
            </div>
          </div>
          <div className='w-7/12 h-1/2 p-10'>
            <TextContainer content={
              <Fragment>
                <div>
                  <span className='text-blue-900 font-bold'>Passioné par les langues</span>
                  <span>, les cultures et les cultures, Alexandra Roque est une auto-entrepreneuse qui a décidé de créer une plateforme de connexion entre les langues.</span>
                </div>
              </Fragment>
            } />
          </div>
        </div>
      </div>
    </div>

  )
}

export default Home
